#
# LICENSE UPL 1.0
#
# Copyright (c) 1982-2020 Oracle and/or its affiliates. All rights reserved.
#
# Since: January, 2020
# Author: gerald.venzl@oracle.com
# Description: Creates an Oracle Linux virtual machine.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# INSTALL PLUGIN RELLOAD
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

# INSTALL PLUGIN VBguest
unless Vagrant.has_plugin?("vagrant-vbguest")
  puts 'Installing vagrant-vbguest Plugin...'
  system('vagrant plugin install vagrant-vbguest')
end

# GLOBAL BOX CONFIGURATIONS
BOX_OL_URL = "https://oracle.github.io/vagrant-projects/boxes"
BOX_OL_NAME = "oraclelinux/9"
BOX_DEBIAN_NAME = "debian/bullseye64"

#DEFINE VM
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # GLOBAL VMGUEST CONFIGURATIONS
  config.vbguest.no_install  = true
  config.vbguest.auto_update = false
  config.vbguest.no_remote   = true
  config.vm.box_download_insecure=true

  # VM ol9_bind_master
  config.vm.define "ol9-bind-master"  do |ol9_bind_master|
    ol9_bind_master.vm.box = BOX_OL_NAME
    ol9_bind_master.vm.box_url = "#{BOX_OL_URL}/#{BOX_OL_NAME}.json"

    # VARIABLE HOSTNAME
    VM_MASTER_NAME= "ol9-bind-master"

    # HOSTNAM
    ol9_bind_master.vm.hostname =VM_MASTER_NAME

    # NETWORK
    ol9_bind_master.vm.network "public_network",ip: "192.168.0.140",mode: "bridge",bridge: "Intel(R) I211 Gigabit Network Connection",nic_type: "virtio"
    ol9_bind_master.vm.network "private_network",ip: "172.36.12.230",nic_type: "virtio"

    # MOUNTS
    ol9_bind_master.vm.synced_folder ".", "/vagrant", disabled: true
    ol9_bind_master.vm.synced_folder "../../Security/", "/home/vagrant/security"
    ol9_bind_master.vm.synced_folder "../../Scripts/lpic2/", "/home/vagrant/scripts"
    ol9_bind_master.vm.synced_folder "./configs", "/home/vagrant/configs"

    # PROVIDER
    ol9_bind_master.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name =VM_MASTER_NAME
      vb.memory = 1024
      vb.cpus = 1
    end

    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    ol9_bind_master.vm.provision "shell", path: "scripts/user-data-bind-master.sh"

  end

  # VM debian_bind_slave
  config.vm.define "debian-bind-slave"  do |debian_bind_slave|
    debian_bind_slave.vm.box = BOX_DEBIAN_NAME

    # VARIABLE HOSTNAME
    VM_SLAVE_NAME= "debian-bind-slave"

    # HOSTNAME
    debian_bind_slave.vm.hostname =VM_SLAVE_NAME

    # NETWORK
    debian_bind_slave.vm.network "public_network",ip: "192.168.0.141",mode: "bridge",bridge: "Intel(R) I211 Gigabit Network Connection"
    debian_bind_slave.vm.network "private_network",ip: "172.36.12.231"

    # MOUNTS
    debian_bind_slave.vm.synced_folder ".", "/vagrant", disabled: true
    debian_bind_slave.vm.synced_folder "../../Security/", "/home/vagrant/security"
    debian_bind_slave.vm.synced_folder "../../Scripts/lpic2/", "/home/vagrant/scripts"
    debian_bind_slave.vm.synced_folder "./configs", "/home/vagrant/configs"

    #PROVIDER
    debian_bind_slave.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name =VM_SLAVE_NAME
      vb.memory = 1024
      vb.cpus = 1
    end

    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    debian_bind_slave.vm.provision "shell", path: "scripts/user-data-bind-slave.sh"
  end

  # VM ol9_apache_ha
  config.vm.define "ol9-apache-ha"  do |ol9_apache_ha|
    ol9_apache_ha.vm.box = BOX_OL_NAME
    ol9_apache_ha.vm.box_url = "#{BOX_OL_URL}/#{BOX_OL_NAME}.json"

    # VARIABLE HOSTNAME
    VM_HA_NAME= "ol9-apache-ha"

    # HOSTNAM
    ol9_apache_ha.vm.hostname =VM_HA_NAME

    # NETWORK
    ol9_apache_ha.vm.network "public_network",ip: "192.168.0.142",mode: "bridge",bridge: "Intel(R) I211 Gigabit Network Connection",nic_type: "virtio"
    ol9_apache_ha.vm.network "private_network",ip: "172.36.12.232",nic_type: "virtio"

    # MOUNTS
    ol9_apache_ha.vm.synced_folder ".", "/vagrant", disabled: true
    ol9_apache_ha.vm.synced_folder "../../Security/", "/home/vagrant/security"
    ol9_apache_ha.vm.synced_folder "./configs", "/home/vagrant/configs"
    ol9_apache_ha.vm.synced_folder "../../Scripts/lpic2/", "/home/vagrant/scripts"

    # PROVIDER
    ol9_apache_ha.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name =VM_HA_NAME
      vb.memory = 2048
      vb.cpus = 1
    end

    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    ol9_apache_ha.vm.provision "shell", path: "scripts/user-data-ol9.sh"

    # CONFIGURE APACHE HTTP
    ol9_apache_ha.vm.provision "shell", path: "scripts/user-data-ol9-apache-ha.sh"

    # GENERATE CERTIFICATES FOR APACHE
    ol9_apache_ha.vm.provision "shell", path: "scripts/generate-certificates.sh" 
  end

  # VM ol9_nginx_ha
  config.vm.define "ol9-nginx-ha"  do |ol9_nginx_ha|
    ol9_nginx_ha.vm.box = BOX_OL_NAME
    ol9_nginx_ha.vm.box_url = "#{BOX_OL_URL}/#{BOX_OL_NAME}.json"

    # VARIABLE HOSTNAME
    VM_HA_NGINX_NAME= "ol9-nginx-ha"

    # HOSTNAM
    ol9_nginx_ha.vm.hostname =VM_HA_NGINX_NAME

    # NETWORK
    ol9_nginx_ha.vm.network "public_network",ip: "192.168.0.143",mode: "bridge",bridge: "Intel(R) I211 Gigabit Network Connection",nic_type: "virtio"
    ol9_nginx_ha.vm.network "private_network",ip: "172.36.12.233",nic_type: "virtio"

    # MOUNTS
    ol9_nginx_ha.vm.synced_folder ".", "/vagrant", disabled: true
    ol9_nginx_ha.vm.synced_folder "../../Security/", "/home/vagrant/security"
    ol9_nginx_ha.vm.synced_folder "./configs", "/home/vagrant/configs"
    ol9_nginx_ha.vm.synced_folder "../../Scripts/lpic2/", "/home/vagrant/scripts"

    # PROVIDER
    ol9_nginx_ha.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name =VM_HA_NGINX_NAME
      vb.memory = 2048
      vb.cpus = 1
    end

    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    ol9_nginx_ha.vm.provision "shell", path: "scripts/user-data-ol9.sh"

    # CONFIGURE NGINX HTTP
    ol9_nginx_ha.vm.provision "shell", path: "scripts/user-data-ol9-nginx-ha.sh"    
  end

  # VM debian_apache_node01
  config.vm.define "debian-apache-node01"  do |debian_apache_node01|
    debian_apache_node01.vm.box = BOX_DEBIAN_NAME

    # VARIABLE HOSTNAME
    VM_NODE01_NAME= "debian-apache-node01"

    # HOSTNAME
    debian_apache_node01.vm.hostname =VM_NODE01_NAME

    # NETWORK
    debian_apache_node01.vm.network "public_network",ip: "192.168.0.144",mode: "bridge",bridge: "Intel(R) I211 Gigabit Network Connection"
    debian_apache_node01.vm.network "private_network",ip: "172.36.12.234"

    # MOUNTS
    debian_apache_node01.vm.synced_folder ".", "/vagrant", disabled: true
    debian_apache_node01.vm.synced_folder "../../Security/", "/home/vagrant/security"
    debian_apache_node01.vm.synced_folder "./configs", "/home/vagrant/configs"
    debian_apache_node01.vm.synced_folder "../../Scripts/lpic2/", "/home/vagrant/scripts"

    #PROVIDER
    debian_apache_node01.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name =VM_NODE01_NAME
      vb.memory = 2048
      vb.cpus = 1
    end

    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    debian_apache_node01.vm.provision "shell", path: "scripts/user-data-debian.sh"

    # CONFIGURE APACHE HTTP
    debian_apache_node01.vm.provision "shell", path: "scripts/user-data-debian-apache-node01.sh"
  end

  # VM debian_apache_node02
  config.vm.define "debian-apache-node02"  do |debian_apache_node02|
    debian_apache_node02.vm.box = BOX_DEBIAN_NAME

    # VARIABLE HOSTNAME
    VM_NODE02_NAME= "debian-apache-node02"

    # HOSTNAME
    debian_apache_node02.vm.hostname =VM_NODE02_NAME

    # NETWORK
    debian_apache_node02.vm.network "public_network",ip: "192.168.0.145",mode: "bridge",bridge: "Intel(R) I211 Gigabit Network Connection"
    debian_apache_node02.vm.network "private_network",ip: "172.36.12.235"

    # MOUNTS
    debian_apache_node02.vm.synced_folder ".", "/vagrant", disabled: true
    debian_apache_node02.vm.synced_folder "../../Security/", "/home/vagrant/security"
    debian_apache_node02.vm.synced_folder "./configs", "/home/vagrant/configs"
    debian_apache_node02.vm.synced_folder "../../Scripts/lpic2/", "/home/vagrant/scripts"

    #PROVIDER
    debian_apache_node02.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name =VM_NODE02_NAME
      vb.memory = 2048
      vb.cpus = 1
    end

    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    debian_apache_node02.vm.provision "shell", path: "scripts/user-data-debian.sh"

    # CONFIGURE APACHE HTTP
    debian_apache_node02.vm.provision "shell", path: "scripts/user-data-debian-apache-node01.sh"
  end

  # VM debian_client
  config.vm.define "debian-http-client"  do |debian_http_client|
    debian_http_client.vm.box = BOX_DEBIAN_NAME

    # VARIABLE HOSTNAME
    VM_CLIENT_NAME= "debian-http-client"

    # HOSTNAME
    debian_http_client.vm.hostname =VM_CLIENT_NAME

    # NETWORK
    debian_http_client.vm.network "public_network",ip: "192.168.0.150",mode: "bridge",bridge: "Intel(R) I211 Gigabit Network Connection"
    debian_http_client.vm.network "private_network",ip: "172.36.12.240"

    # MOUNTS
    debian_http_client.vm.synced_folder ".", "/vagrant", disabled: true
    debian_http_client.vm.synced_folder "../../Security/", "/home/vagrant/security"
    debian_http_client.vm.synced_folder "./configs", "/home/vagrant/configs"
    debian_http_client.vm.synced_folder "./test", "/home/vagrant/test"
    debian_http_client.vm.synced_folder "../../Scripts/lpic2/", "/home/vagrant/scripts"

    #PROVIDER
    debian_http_client.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name =VM_CLIENT_NAME
      vb.memory = 8192
      vb.cpus = 3
    end

    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    debian_http_client.vm.provision "shell", path: "scripts/user-data-debian.sh"

    # CONFIGURE CLIENT HTTP CLIENT
    debian_http_client.vm.provision "shell", path: "scripts/user-data-debian-http-client.sh"

    # CHECK HTTP STACK
    debian_http_client.vm.provision "shell", path: "scripts/check-http-stack.sh"
  end

end