#
# LICENSE UPL 1.0
#
# Copyright (c) 1982-2020 Oracle and/or its affiliates. All rights reserved.
#
# Since: January, 2020
# Author: gerald.venzl@oracle.com
# Description: Creates an Oracle Linux virtual machine.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'fileutils'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# INSTALL PLUGIN RELLOAD
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

# INSTALL PLUGIN VBguest
unless Vagrant.has_plugin?("vagrant-vbguest")
  puts 'Installing vagrant-vbguest Plugin...'
  system('vagrant plugin install vagrant-vbguest')
end

#Define VM
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # VM ol9_bind_master
  config.vm.define "ol9-bind-master"  do |ol9_bind_master|
    # Box metadata location and box name
    BOX_URL = "https://oracle.github.io/vagrant-projects/boxes"
    BOX_NAME = "oraclelinux/9"
    ol9_bind_master.vm.box = BOX_NAME
    ol9_bind_master.vm.box_url = "#{BOX_URL}/#{BOX_NAME}.json"
    ol9_bind_master.vm.box_download_insecure=true
    ol9_bind_master.vbguest.no_install  = true
    ol9_bind_master.vbguest.auto_update = false
    ol9_bind_master.vbguest.no_remote   = true


    # VARIABLE HOSTNAME
    VM_MASTER_NAME= "ol9-bind-master"

    # HOSTNAM
    ol9_bind_master.vm.hostname =VM_MASTER_NAME

    # NETWORK
    ol9_bind_master.vm.network "public_network",ip: "192.168.0.140",mode: "bridge",bridge: "Intel(R) I211 Gigabit Network Connection",nic_type: "virtio"
    ol9_bind_master.vm.network "private_network",ip: "172.36.12.230",nic_type: "virtio"

    # MOUNTS
    ol9_bind_master.vm.synced_folder ".", "/vagrant", disabled: true
    ol9_bind_master.vm.synced_folder "../../Security/", "/home/vagrant/security"
    ol9_bind_master.vm.synced_folder "./configs", "/home/vagrant/configs"
    ol9_bind_master.vm.synced_folder "../../Scripts/lpic2/", "/home/vagrant/scripts"

    # PROVIDER
    ol9_bind_master.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name =VM_MASTER_NAME
      vb.memory = 2048
      vb.cpus = 2
    end

    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    ol9_bind_master.vm.provision "shell", path: "scripts/user-data-bind-master.sh"

  end

  # VM debian_bind_slave
  config.vm.define "debian-bind-slave"  do |debian_bind_slave|
    debian_bind_slave.vm.box = "debian/bullseye64"
    debian_bind_slave.vm.box_download_insecure=true
    debian_bind_slave.vbguest.no_install  = true
    debian_bind_slave.vbguest.auto_update = false
    debian_bind_slave.vbguest.no_remote   = true

    # VARIABLE HOSTNAME
    VM_SLAVE_NAME= "debian-bind-slave"

    # HOSTNAME
    debian_bind_slave.vm.hostname =VM_SLAVE_NAME

    # NETWORK
    debian_bind_slave.vm.network "public_network",ip: "192.168.0.141",mode: "bridge",bridge: "Intel(R) I211 Gigabit Network Connection"
    debian_bind_slave.vm.network "private_network",ip: "172.36.12.231"

    # MOUNTS
    debian_bind_slave.vm.synced_folder ".", "/vagrant", disabled: true
    debian_bind_slave.vm.synced_folder "../../Security/", "/home/vagrant/security"
    debian_bind_slave.vm.synced_folder "./configs", "/home/vagrant/configs"
    debian_bind_slave.vm.synced_folder "../../Scripts/lpic2/", "/home/vagrant/scripts"

    #PROVIDER
    debian_bind_slave.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name =VM_SLAVE_NAME
      vb.cpus = 2
    end

    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    debian_bind_slave.vm.provision "shell", path: "scripts/user-data-bind-slave.sh"

  end

  #VM ol9_bind_caching
  config.vm.define "ol9-bind-caching"  do |ol9_bind_caching|
    BOX_URL = "https://oracle.github.io/vagrant-projects/boxes"
    BOX_NAME = "oraclelinux/9"
    ol9_bind_caching.vm.box = BOX_NAME
    ol9_bind_caching.vm.box_url = "#{BOX_URL}/#{BOX_NAME}.json"
    ol9_bind_caching.vm.box_download_insecure=true
    ol9_bind_caching.vbguest.no_install  = true
    ol9_bind_caching.vbguest.auto_update = false
    ol9_bind_caching.vbguest.no_remote   = true

    # VARIABLE HOSTNAME
    VM_CACHING_NAME= "ol9-bind-caching"

    # HOSTNAME
    ol9_bind_caching.vm.hostname =VM_CACHING_NAME

    # NETWORK
    ol9_bind_caching.vm.network "public_network",ip: "192.168.0.145",mode: "bridge",bridge: "Intel(R) I211 Gigabit Network Connection",nic_type: "virtio"
    ol9_bind_caching.vm.network "private_network",ip: "172.36.12.235",nic_type: "virtio"

    # MOUNTS
    ol9_bind_caching.vm.synced_folder ".", "/vagrant", disabled: true
    ol9_bind_caching.vm.synced_folder "../../Security/", "/home/vagrant/security"
    ol9_bind_caching.vm.synced_folder "./configs", "/home/vagrant/configs"
    ol9_bind_caching.vm.synced_folder "../../Scripts/lpic2/", "/home/vagrant/scripts"

    # PROVIDER
    ol9_bind_caching.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name =VM_CACHING_NAME
      vb.memory = 2048
      vb.cpus = 2
    end

    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    ol9_bind_caching.vm.provision "shell", path: "scripts/user-data-bind-caching.sh"

  end
end