# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# INSTALL PLUGIN RELLOAD
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "generic/fedora28"
  config.vm.box_download_insecure=true
  config.vbguest.no_install  = true
  config.vbguest.auto_update = false
  config.vbguest.no_remote   = true

  # VM srv01
  config.vm.define "fedora-lpic2-202"  do |fedora_lpic2_202|

    # VARIABLE HOSTNAME
    APP_NAME= "fedora-lpic-202"

    # HOSTNAME
    fedora_lpic2_202.vm.hostname = APP_NAME

    # NETWORK
    fedora_lpic2_202.vm.network "public_network" ,ip: "192.168.0.139",mode: "bridge",bridge: [
    "ens32",
    "Intel(R) I211 Gigabit Network Connection"
    ]

    # MOUNTS
    fedora_lpic2_202.vm.synced_folder ".", "/vagrant", disabled: true
    fedora_lpic2_202.vm.synced_folder "../../Security/", "/home/vagrant/security"
    fedora_lpic2_202.vm.synced_folder "./configs", "/home/vagrant/configs"

    # PROVIDER
    fedora_lpic2_202.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name = APP_NAME
      vb.memory = 2048
      vb.cpus = 1
    end

   # SHELL PROVISIONING
    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    fedora_lpic2_202.vm.provision "shell", path: "scripts/install.sh"

  end

end